spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: todolist-api
management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /api/actuator
  health:
    db:
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /api